<footer style="border-top: 4px solid #023d4f;
            padding-top: 15px;">
    <a href="https://swin-cos10026.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiNzhkNzI1MTMwOTYzNDQ3NmFmMzI3ODFiNDQxNmQ1MmQiLCJwIjoiaiJ9"
        id="COS10026_Group05_Jira_Link">Group05 Jira Link</a>
    <p><a href="https://github.com/swin106179841/WT-Applied-Web-Project-G5.git" id="COS10026_Group05GitHub_Link">Group05
            GitHub Link</a></p>
    <p>Email EcoSphere Alliance At: <a href="mailto:EcoSphereAlliance@email.com"
            title="EcoSphere Alliance Email">EcoSphereAlliance@email.com</a></p>
</footer>