<header>
        <nav>
            <ul>
                <li><a href="./index.php" id="nav-home"><img src="./assets/logo-no-bg.png"
                            alt="EcoSphere company logo"></a></li>
                <li><a href="./jobs.php">Jobs</a></li>
                <li><a href="./apply.php">Apply</a></li>
                <li><a href="./about.php">About</a></li>
            </ul>
        </nav>
    </header>